version: '3.7'

services:
   employee-service:
      image: employee/employee:0.0.1-SNAPSHOT
      
      ports: 
         - "8080:8080"
      
      environment:
         - "SPRING_PROFILES_ACTIVE=dev"
         
      networks:
         backend:
            aliases:
               - "employeeservice"
            
networks:
   backend:
      driver: bridge